// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OnTrack.Backend.Api.Migrations
{
	/// <inheritdoc />
	public partial class AddedPredecessorsAndSuccessorsCollectionsToTaskEntity : Migration
	{
		/// <inheritdoc />
		protected override void Up(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.DropForeignKey(
				name: "FK_Tasks_Tasks_TaskId",
				table: "Tasks");

			migrationBuilder.RenameColumn(
				name: "TaskId",
				table: "Tasks",
				newName: "SuccessorId");

			migrationBuilder.RenameIndex(
				name: "IX_Tasks_TaskId",
				table: "Tasks",
				newName: "IX_Tasks_SuccessorId");

			migrationBuilder.AddColumn<Guid>(
				name: "PredecessorId",
				table: "Tasks",
				type: "uniqueidentifier",
				nullable: true);

			migrationBuilder.AddColumn<Guid>(
				name: "SubtaskId",
				table: "Tasks",
				type: "uniqueidentifier",
				nullable: true);

			migrationBuilder.CreateIndex(
				name: "IX_Tasks_PredecessorId",
				table: "Tasks",
				column: "PredecessorId");

			migrationBuilder.CreateIndex(
				name: "IX_Tasks_SubtaskId",
				table: "Tasks",
				column: "SubtaskId");

			migrationBuilder.AddForeignKey(
				name: "FK_Tasks_Tasks_PredecessorId",
				table: "Tasks",
				column: "PredecessorId",
				principalTable: "Tasks",
				principalColumn: "Id");

			migrationBuilder.AddForeignKey(
				name: "FK_Tasks_Tasks_SubtaskId",
				table: "Tasks",
				column: "SubtaskId",
				principalTable: "Tasks",
				principalColumn: "Id");

			migrationBuilder.AddForeignKey(
				name: "FK_Tasks_Tasks_SuccessorId",
				table: "Tasks",
				column: "SuccessorId",
				principalTable: "Tasks",
				principalColumn: "Id");
		}

		/// <inheritdoc />
		protected override void Down(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.DropForeignKey(
				name: "FK_Tasks_Tasks_PredecessorId",
				table: "Tasks");

			migrationBuilder.DropForeignKey(
				name: "FK_Tasks_Tasks_SubtaskId",
				table: "Tasks");

			migrationBuilder.DropForeignKey(
				name: "FK_Tasks_Tasks_SuccessorId",
				table: "Tasks");

			migrationBuilder.DropIndex(
				name: "IX_Tasks_PredecessorId",
				table: "Tasks");

			migrationBuilder.DropIndex(
				name: "IX_Tasks_SubtaskId",
				table: "Tasks");

			migrationBuilder.DropColumn(
				name: "PredecessorId",
				table: "Tasks");

			migrationBuilder.DropColumn(
				name: "SubtaskId",
				table: "Tasks");

			migrationBuilder.RenameColumn(
				name: "SuccessorId",
				table: "Tasks",
				newName: "TaskId");

			migrationBuilder.RenameIndex(
				name: "IX_Tasks_SuccessorId",
				table: "Tasks",
				newName: "IX_Tasks_TaskId");

			migrationBuilder.AddForeignKey(
				name: "FK_Tasks_Tasks_TaskId",
				table: "Tasks",
				column: "TaskId",
				principalTable: "Tasks",
				principalColumn: "Id");
		}
	}
}
